apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cqrs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
        - name: container-dotnet-app
          image: mdmago/demo-cqrs:version1