version: "3.3"

services:
  demo_cqrs:
    container_name: democqrs
    image: demo-cqrs
    volumes:
      - dotnet-volume-app:/data
    networks:
      - service-api
    restart: always
    env_file:
      - ./.env
    ports:
      - 5000:80

  sql_db:
    container_name: sqldb
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - sqldb:/data
    networks:
      - service-api
    restart: always
    env_file:
      - ./.db.env
    ports:
      - 8000:1433

volumes:
  dotnet-volume-app: {}
  sqldb: {}

networks:
  service-api: {}